### ISSUE TITLE
NPC's out of bounds hacky fix

### ISSUE THREAD

**Issue by ParchmentWolf** [michaelsakharov/OrionPlusSharp#5]
After looking at the code it appears what was wrong was the "CanNpcMove" variable was what was being set on proper checks, however it was never checked as a return condition thus making the previous checks useless. I am sending a PR that both fixes that and revamps the entire function to be significantly cleaner (And should be more optimized)

**Comment by michaelsakharov** [comment]
Merged.
Thanks!!!
